server:
  port: 8080

spring:
  application:
    name: shipment-tracking-system

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:shipment_tracking}
    username: ${DB_USERNAME:shipment_user}
    password: ${DB_PASSWORD:shipment_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug